# Generated by Django 3.2.6 on 2021-08-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllEmail', models.EmailField(max_length=100, unique=True)),
                ('AllPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Create', models.DateField(auto_now_add=True)),
                ('ProfilePic', models.ImageField(upload_to='Practice/')),
                ('alldata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.alldata')),
            ],
        ),
    ]
